services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566" # port principal de localstack
    environment:
      - SERVICES=s3,kms # services AWS (S3, KMS) qu'on va tester avec LocalStack
      - DEBUG=1
    volumes:
      - "./localstack_data:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python-app
    volumes:
      - ./app:/app
    working_dir: /app
    command: tail -f /dev/null
    depends_on:
      - localstack
